server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-db
    username: m1guelsb
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
cors:
  originPatterns: "http://localhost:3000"