server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-db
    username: m1guelsb
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false